name: Update Spheron Cluster Instance

on:
  push:
    branches:
      - main

jobs:
  update-spheron-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version
        id: extract-version
        run: echo "version=$(cat version.json | jq -r '.version')" >> "$GITHUB_OUTPUT"

      - name: Print version
        run: echo ${{ steps.extract-version.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vocoront/simple-dotnet:${{ steps.extract-version.outputs.version }}
        

      - name: Update Spheron Instance
        id: updaing-instance
        uses: decent-infra/shomix-car-update-action@v1.3
        with:
          spheron-token:  ${{ secrets.SPHERON_TOKEN }}
          instance-id: "646b3ce402397f00124a10e1"
          tag: ${{ steps.extract-version.outputs.version }}
          env: "key1=value1,key2=value2"
          secret-env: "skey1=s1,skey2=s2"